---
title: "Fig4c"
author: "Emmanuel Tergemina"
date: "2024-03-11"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r library, message=F, warning=F}
library(ggmap)
library(ggrepel)
library(maps)
library(mapproj)
library(plyr)
library(dplyr)
```

## Set map
```{r map, message=F, warning=F}
Map = c(left = -20, bottom = 32, right = 45, top = 70) #Europe
mapacc <- get_stadiamap(Map, zoom = 5, maptype = c("stamen_toner_background")) #download_map
```
## Import data
```{r import}
df <- read.table("Fig4c.txt", header = T, sep = '\t')
```

## Plotting
```{r plotting}
reorder <- df[order(df$Chr5_21392702, decreasing=FALSE), ]
reorder <- reorder%>%filter(Chr5_21392702!='.')
ggmap(mapacc) +
  labs(x = 'Longitude', y = 'Latitude',color = "chr5:21392702",shape=3) +
  geom_point(data=reorder, aes(x = Longitude,y = Latitude, color = Chr5_21392702),
             size=1,alpha=0.6) +
  scale_color_manual(values = c("0" = "#56B4E9","1" = "red"),labels = c("major", "minor"),) 
```
